### PR TITLE
feat: update helm chart version

### PR DESCRIPTION
**Pull request by immanuelfodor**
Update the agent version and add an OAS by URL example.

The old contents of this PR have been already applied by https://github.com/traefik-workshops/traefik-hub-gitops/pull/42

> Related to https://github.com/traefik/hub-issues/issues/913#issuecomment-1874099679
> Merge this PR once Granularity is released.
> The `port` field was removed in https://github.com/traefik/traefik-hub/pull/122 and https://github.com/traefik/hub-api-management/pull/130
> There is an explanation in the PR that this field was never used, so the assumption is that the port for the OAS is the same as the service port. 
> If somebody needs a workaround to use the same service but with a different port, they can enter a custom in-cluster URL for the `url` field like `http://customer-app.apps:5555/openapi.yaml` or `http://customer-app.apps.svc.cluster.local:5555/openapi.yaml`

### CODE REVIEW

**Review by mloiseleur — APPROVED** [review]

**Comment by mloiseleur** [comment]
no-merge until the feature is released.

**Comment by immanuelfodor** [comment]
The latest traefik-hub agent release is v2.6.0 from 21 Nov, and both https://github.com/traefik/traefik-hub/pull/122 and https://github.com/traefik/hub-api-management/pull/130 are more recent than that, so I think we still don't have them published, it's only available in the dev image. 

> Merge this PR once Granularity is released.

This is what still blocking the merge to have a new public agent build.

**Comment by immanuelfodor** [comment]
Updated Hub, I think we can now merge @mloiseleur

**Comment by mloiseleur** [comment]
It needs to be rebased and tested first

**Comment by immanuelfodor** [comment]
It looks like Rémi has already removed the ports in https://github.com/traefik-workshops/traefik-hub-gitops/pull/42 so now this PR is basically just the update of the agent :sweat_smile:

**Comment by immanuelfodor** [comment]
Tested it with the Prod env, it works as expected :tada:

**Pull request merged**
